In [1]:
import pandas as pd
from supabase import create_client

# 1. & 2. Ühendamine ja andmete laadimine Supabase'ist
try:
    URL = "https://xwmwqxqorsiauliaynkk.supabase.co"
    KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3bXdxeHFvcnNpYXVsaWF5bmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2OTYyNDQsImV4cCI6MjA5NzI3MjI0NH0.e6JbKi_zYsXDaASplLrqnt8ZZnZdPiET7l0PdzZguZE"

    supabase = create_client(URL, KEY)

    sales_res = supabase.table("sales").select("*").execute()
    df_sales = pd.DataFrame(sales_res.data)

    customers_res = supabase.table("customers").select("*").execute()
    df_customers = pd.DataFrame(customers_res.data)
    print("✅ Andmed laeti edukalt Supabase'ist!\n")

except Exception as e:
    print("⚠️ Supabase ei toiminud, laadime lokaalsetest CSV-failidest...")
    df_sales = pd.read_csv("sales.csv")
    df_customers = pd.read_csv("customers.csv")
    print("✅ Andmed laeti CSV-failidest!\n")

✅ Andmed laeti edukalt Supabase'ist!

In [2]:
# 3. Sales tabeli kontroll
print("--- 1. SALES TABEL ---")
print("Sales tabeli shape:", df_sales.shape)
print(df_sales.head())

--- 1. SALES TABEL ---
Sales tabeli shape: (1000, 12)
   id  sale_id        invoice_id            sale_date  customer_id  \
0   1        1  INV-202301-00001  2023-01-10T00:00:00       2588.0
1   2        2  INV-202301-00002  2023-01-16T00:00:00       4338.0
2   3        3  INV-202301-00003  2023-01-05T00:00:00       4673.0
3   4        4  INV-202301-00004  2023-01-02T00:00:00       4677.0
4   5        5  INV-202301-00005  2023-01-13T00:00:00       2390.0

   product_id  quantity  unit_price  total_price channel store_location  \
0        1274         2      234.79       469.58    pood        Tallinn
1        1207         2      241.13       482.26    pood          Pärnu
2        1264         1      258.46       221.19    pood          Pärnu
3        1341         3       45.21       135.63    pood          Tartu
4        1284         1       99.57        99.57    pood          Tartu

  payment_method
0          kaart
1      järelmaks
2      järelmaks
3       sularaha
4          kaart

In [3]:
# 4. Customers tabeli kontroll
print("\n--- 2. CUSTOMERS TABEL ---")
print("Customers tabeli shape:", df_customers.shape)
print(df_customers.head())

--- 2. CUSTOMERS TABEL ---
Customers tabeli shape: (1000, 9)
   customer_id first_name last_name                   email           phone  \
0         2001        Eha       Aas        eha.aas@telia.ee  +372 8713 1455
1         2002      Aivar      Kõiv  aivar.koiv@outlook.com  +372 8943 8684
2         2003      Maris    Rebane   maris.rebane@telia.ee  +372 5918 5726
3         2005      Raivo    Koppel  raivo.koppel@yahoo.com  +372 5298 4365
4         2006       Aili      Must                    None  +372 5444 0491

       city registration_date loyalty_tier  birth_year
0   Tallinn        2024-02-27         None        1973
1  Haapsalu        2025-01-09       bronze        1988
2     Tartu        2021-02-03         None        1999
3   Tallinn        2023-05-22       bronze        2004
4     Pärnu        2022-01-04         None        1986

In [4]:
# 5. Liidame tabelid
df = pd.merge(df_sales, df_customers, on="customer_id", how="left")

In [5]:
print(df.shape)

(1000, 20)

In [6]:
print("Esialgne shape:", df.shape)

# Duplikaadid
print("Duplikaadid:", df.duplicated(subset=['invoice_id']).sum())
df = df.drop_duplicates(subset=['invoice_id'], keep='first')

# NULL väärtused
print("\nNULL väärtused:")
print(df.isnull().sum())

df = df.dropna(subset=['customer_id', 'sale_date', 'total_price'])

# Kuupäev datetime-ks
df['sale_date'] = pd.to_datetime(df['sale_date'])

# Negatiivsed hinnad
df = df[df['total_price'] > 0]

# Puhastusraport
print("\n===== PUHASTUSRAPORT =====")
print("Lõplik shape:", df.shape)
print("Unikaalseid kliente:", df['customer_id'].nunique())
print("Kuupäevavahemik:",
      df['sale_date'].min(),
      "kuni",
      df['sale_date'].max())

df.head()

Esialgne shape: (1000, 20)
Duplikaadid: 0

NULL väärtused:
id                     0
sale_id                0
invoice_id             0
sale_date              0
customer_id           77
product_id             0
quantity               0
unit_price             0
total_price            0
channel                0
store_location       312
payment_method         0
first_name           724
last_name            724
email                752
phone                724
city                 724
registration_date    724
loyalty_tier         826
birth_year           724
dtype: int64

===== PUHASTUSRAPORT =====
Lõplik shape: (907, 20)
Unikaalseid kliente: 661
Kuupäevavahemik: 2023-01-01 00:00:00 kuni 2026-03-17 00:00:00

,id,sale_id,invoice_id,sale_date,customer_id,product_id,quantity,unit_price,total_price,channel,store_location,payment_method,first_name,last_name,email,phone,city,registration_date,loyalty_tier,birth_year
0,1,1,INV-202301-00001,2023-01-10,2588.0,1274,2,234.79,469.58,pood,Tallinn,kaart,Hille,Paju,None,+372 5429 0294,Tallinn,2022-07-28,bronze,1997.0
1,2,2,INV-202301-00002,2023-01-16,4338.0,1207,2,241.13,482.26,pood,Pärnu,järelmaks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,INV-202301-00003,2023-01-05,4673.0,1264,1,258.46,221.19,pood,Pärnu,järelmaks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,INV-202301-00004,2023-01-02,4677.0,1341,3,45.21,135.63,pood,Tartu,sularaha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,INV-202301-00005,2023-01-13,2390.0,1284,1,99.57,99.57,pood,Tartu,kaart,Triin,Lill,triin.lill@telia.ee,+372 5378 0596,Tartu,2021-04-09,None,1996.0

In [ ]:
print("\n--- 3. LIIDATUD DATAFRAME (df) ---")
print("Liidatud tabeli shape:", df.shape)
print("\nVeergude tüübid (dtypes):")
print(df.dtypes)
print("\nEsimesed 5 rida (head):")
print(df.head())

--- 3. LIIDATUD DATAFRAME (df) ---
Liidatud tabeli shape: (1000, 20)

Veergude tüübid (dtypes):
id                     int64
sale_id                int64
invoice_id               str
sale_date                str
customer_id          float64
product_id             int64
quantity               int64
unit_price           float64
total_price          float64
channel                  str
store_location           str
payment_method           str
first_name               str
last_name                str
email                    str
phone                    str
city                     str
registration_date        str
loyalty_tier             str
birth_year           float64
dtype: object

Esimesed 5 rida (head):
   id  sale_id        invoice_id            sale_date  customer_id  \
0   1        1  INV-202301-00001  2023-01-10T00:00:00       2588.0
1   2        2  INV-202301-00002  2023-01-16T00:00:00       4338.0
2   3        3  INV-202301-00003  2023-01-05T00:00:00       4673.0
3   4        4  INV-202301-00004  2023-01-02T00:00:00       4677.0
4   5        5  INV-202301-00005  2023-01-13T00:00:00       2390.0

   product_id  quantity  unit_price  total_price channel store_location  \
0        1274         2      234.79       469.58    pood        Tallinn
1        1207         2      241.13       482.26    pood          Pärnu
2        1264         1      258.46       221.19    pood          Pärnu
3        1341         3       45.21       135.63    pood          Tartu
4        1284         1       99.57        99.57    pood          Tartu

  payment_method first_name last_name                email           phone  \
0          kaart      Hille      Paju                  NaN  +372 5429 0294
1      järelmaks        NaN       NaN                  NaN             NaN
2      järelmaks        NaN       NaN                  NaN             NaN
3       sularaha        NaN       NaN                  NaN             NaN
4          kaart      Triin      Lill  triin.lill@telia.ee  +372 5378 0596

      city registration_date loyalty_tier  birth_year
0  Tallinn        2022-07-28       bronze      1997.0
1      NaN               NaN          NaN         NaN
2      NaN               NaN          NaN         NaN
3      NaN               NaN          NaN         NaN
4    Tartu        2021-04-09          NaN      1996.0

In [ ]:
# Seadistame Pandas'i kuvama kõiki veerge
pd.set_option('display.max_columns', None)

print("--- LIIDATUD TABELI ESIMESED READ ---")
display(df.head())

print("\n--- ANDMETE ÜLDULEVAATUS ---")
df.info()

--- LIIDATUD TABELI ESIMESED READ ---

,id,sale_id,invoice_id,sale_date,customer_id,product_id,quantity,unit_price,total_price,channel,store_location,payment_method,first_name,last_name,email,phone,city,registration_date,loyalty_tier,birth_year
0,1,1,INV-202301-00001,2023-01-10T00:00:00,2588.0,1274,2,234.79,469.58,pood,Tallinn,kaart,Hille,Paju,NaN,+372 5429 0294,Tallinn,2022-07-28,bronze,1997.0
1,2,2,INV-202301-00002,2023-01-16T00:00:00,4338.0,1207,2,241.13,482.26,pood,Pärnu,järelmaks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,INV-202301-00003,2023-01-05T00:00:00,4673.0,1264,1,258.46,221.19,pood,Pärnu,järelmaks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,INV-202301-00004,2023-01-02T00:00:00,4677.0,1341,3,45.21,135.63,pood,Tartu,sularaha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5,INV-202301-00005,2023-01-13T00:00:00,2390.0,1284,1,99.57,99.57,pood,Tartu,kaart,Triin,Lill,triin.lill@telia.ee,+372 5378 0596,Tartu,2021-04-09,NaN,1996.0

--- ANDMETE ÜLDULEVAATUS ---
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1000 non-null   int64
 1   sale_id            1000 non-null   int64
 2   invoice_id         1000 non-null   str
 3   sale_date          1000 non-null   str
 4   customer_id        923 non-null    float64
 5   product_id         1000 non-null   int64
 6   quantity           1000 non-null   int64
 7   unit_price         1000 non-null   float64
 8   total_price        1000 non-null   float64
 9   channel            1000 non-null   str
 10  store_location     688 non-null    str
 11  payment_method     1000 non-null   str
 12  first_name         276 non-null    str
 13  last_name          276 non-null    str
 14  email              248 non-null    str
 15  phone              276 non-null    str
 16  city               276 non-null    str
 17  registration_date  276 non-null    str
 18  loyalty_tier       174 non-null    str
 19  birth_year         276 non-null    float64
dtypes: float64(4), int64(4), str(12)
memory usage: 224.4 KB

In [1]:
1 + 1

2